### ISSUE TITLE
Add Portuguese Translations

### ISSUE THREAD

**Issue by realdm** [realdm/mpesasdk#13]
**Is your feature request related to a problem? Please describe.**
This library is going to be used mostly by people from Mozambique and with that assumption in mind, I think we should add Portuguese translations to the strings that will be picked up automatically if the user has Portuguese as the priority language.

**Describe the solution you'd like**
Add string resource variant for Portuguese.

**Describe alternatives you've considered**

**Additional context**

**Comment by EdNgulele** [comment]
Hello @realdm 
I'd love to do it, please assign me to it if no one else is working on it.
